-- V1: the two tables every module uses: configurable business rules (S19) and the audit log (BR-14).
-- Plan rule: BR values are configured, never hard-coded in Java.
CREATE TABLE app_settings (
    setting_key   VARCHAR(80)  PRIMARY KEY,
    setting_value VARCHAR(255) NOT NULL,
    value_type    VARCHAR(10)  NOT NULL CHECK (value_type IN ('INT', 'STRING', 'BOOL')),
    min_value     INT,
    max_value     INT,
    description   VARCHAR(255) NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by    BIGINT
);

INSERT INTO app_settings (setting_key, setting_value, value_type, min_value, max_value, description) VALUES
('auth.allowed-email-domains',    'fpt.edu.vn,fe.edu.vn', 'STRING', NULL, NULL, 'BR-01 email domains allowed to self-register (comma separated)'),
('auth.max-failed-logins',        '5',  'INT', 3, 10,   'BR-02 wrong passwords in a row before a temporary lock'),
('auth.lock-minutes',             '15', 'INT', 1, 1440, 'BR-02 temporary lock length (minutes)'),
('auth.reset-token-minutes',      '30', 'INT', 5, 1440, 'BR-03 password reset link lifetime (minutes)'),
('auth.verify-token-hours',       '24', 'INT', 1, 168,  'Email verification link lifetime (hours)'),
('booking.slot-minutes',          '30', 'INT', 15, 60,  'BR-04 bookings are multiples of this many minutes'),
('booking.max-advance-days',      '14', 'INT', 1, 60,   'BR-05 how far ahead a booking may start (days)'),
('booking.max-hours-per-week',    '6',  'INT', 1, 40,   'BR-05 student quota (hours per week)'),
('booking.approval-capacity',     '30', 'INT', 1, 500,  'BR-06 labs with MORE seats than this need approval'),
('booking.free-cancel-hours',     '2',  'INT', 0, 72,   'BR-07 free cancellation until this many hours before start'),
('checkin.window-minutes',        '15', 'INT', 5, 60,   'BR-08 check-in window before/after start (minutes)'),
('waitlist.hold-minutes',         '10', 'INT', 1, 120,  'BR-10 how long a promoted waitlist entry is held (minutes)'),
('loan.default-days',             '3',  'INT', 1, 30,   'BR-12 default loan length (days)');

-- BR-14: append-only. The app only INSERTs here (entity is @Immutable); nobody edits or deletes audit rows.
CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id    BIGINT,
    entity      VARCHAR(40) NOT NULL,
    entity_id   VARCHAR(40) NOT NULL,
    action      VARCHAR(40) NOT NULL,
    before_data TEXT,
    after_data  TEXT,
    at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_entity ON audit_logs (entity, entity_id);
