-- V2: users, roles, tokens (E2 Identity & RBAC). Roles follow the ERD in the plan.
CREATE TABLE roles (
    id   INT PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL
);
INSERT INTO roles (id, code, name) VALUES
(1, 'STUDENT',  'Student'),
(2, 'LECTURER', 'Lecturer'),
(3, 'STAFF',    'Lab Staff'),
(4, 'MANAGER',  'Lab Manager'),
(5, 'ADMIN',    'Admin');

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    full_name     VARCHAR(100) NOT NULL,
    phone         VARCHAR(15),
    avatar_url    VARCHAR(500),
    status        VARCHAR(10)  NOT NULL CHECK (status IN ('PENDING', 'ACTIVE', 'LOCKED')),
    failed_logins INT          NOT NULL DEFAULT 0,
    locked_until  TIMESTAMP WITH TIME ZONE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users (id),
    role_id INT    NOT NULL REFERENCES roles (id),
    PRIMARY KEY (user_id, role_id)
);

-- One table for every one-time token: email verification, password reset, refresh.
-- Only the SHA-256 hash is stored, never the token itself.
CREATE TABLE user_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id),
    purpose    VARCHAR(10) NOT NULL CHECK (purpose IN ('VERIFY', 'RESET', 'REFRESH')),
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at    TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_user_tokens_user ON user_tokens (user_id, purpose);
