-- V3: campus -> building -> lab (E2 day 18).
CREATE TABLE campuses (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20)  NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE buildings (
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id INT          NOT NULL REFERENCES campuses (id),
    code      VARCHAR(20)  NOT NULL UNIQUE,
    name      VARCHAR(100) NOT NULL,
    status    VARCHAR(10)  NOT NULL CHECK (status IN ('ACTIVE', 'CLOSED'))
);

CREATE TABLE labs (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id       INT          NOT NULL REFERENCES buildings (id),
    code              VARCHAR(20)  NOT NULL UNIQUE,
    name              VARCHAR(100) NOT NULL,
    floor             INT          NOT NULL CHECK (floor BETWEEN 0 AND 50),
    capacity          INT          NOT NULL CHECK (capacity > 0),
    status            VARCHAR(10)  NOT NULL CHECK (status IN ('ACTIVE', 'CLOSED')),
    requires_approval BOOLEAN      NOT NULL DEFAULT FALSE,
    version           INT          NOT NULL DEFAULT 0
);
