-- V4: resource catalog (E3 day 22): equipment types and equipment units.
CREATE TABLE equipment_types (
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               VARCHAR(20)  NOT NULL UNIQUE,
    name               VARCHAR(100) NOT NULL
);

CREATE TABLE equipment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_id            INT          NOT NULL REFERENCES labs (id),
    type_id           INT          NOT NULL REFERENCES equipment_types (id),
    serial            VARCHAR(50)  NOT NULL UNIQUE,
    name              VARCHAR(100) NOT NULL,
    status            VARCHAR(12)  NOT NULL CHECK (status IN ('AVAILABLE', 'ON_LOAN', 'MAINTENANCE', 'RETIRED')),
    requires_training BOOLEAN      NOT NULL DEFAULT FALSE,
    requires_approval BOOLEAN      NOT NULL DEFAULT FALSE,
    status_reason     VARCHAR(255),
    version           INT          NOT NULL DEFAULT 0
);
CREATE INDEX idx_equipment_lab ON equipment (lab_id, status);
