-- V5: operating calendar (E3 day 23 / S18). Times are Vietnam local time (ADR-002).
-- lab_id NULL = default hours for every lab; a row with lab_id overrides the default for that lab.
CREATE TABLE operating_hours (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_id      INT REFERENCES labs (id),
    day_of_week INT     NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),  -- 1 = Monday (ISO-8601)
    open_time   TIME,
    close_time  TIME,
    closed      BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_operating_hours ON operating_hours (lab_id, day_of_week);

CREATE TABLE blackouts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_id     INT          NOT NULL REFERENCES labs (id),
    start_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    reason     VARCHAR(255) NOT NULL,
    created_by BIGINT,
    CHECK (start_at < end_at)
);
CREATE INDEX idx_blackouts_lab ON blackouts (lab_id, start_at);

CREATE TABLE holidays (
    holiday_date DATE PRIMARY KEY,
    name         VARCHAR(100) NOT NULL
);
