-- V6: reservation tables from the transaction spike (E1 day 11). Half-open period [start_at, end_at).
CREATE TABLE reservations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES users (id),
    status          VARCHAR(12)  NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELLED', 'CHECKED_IN', 'NO_SHOW', 'COMPLETED')),
    start_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    purpose         VARCHAR(255) NOT NULL,
    idempotency_key VARCHAR(64)  NOT NULL UNIQUE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version         INT          NOT NULL DEFAULT 0,
    CHECK (start_at < end_at)
);

-- The period is copied here so that ONE table can carry the anti-double-booking constraint.
CREATE TABLE reservation_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT  NOT NULL REFERENCES reservations (id),
    lab_id         INT     REFERENCES labs (id),
    equipment_id   BIGINT  REFERENCES equipment (id),
    start_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    active         BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK ((lab_id IS NULL) <> (equipment_id IS NULL))
);
CREATE INDEX idx_items_lab_time ON reservation_items (lab_id, start_at, end_at);
